jobs:
## CI for BOX
#  - name: box-ci
#    type: runCI
#    steps:
#      - IN: box-repo
#      - IN: box-img

## manifest gen for BOX
#  - name: box-man
#    type: manifest
#    steps:
#      - IN: box-img
#      - IN: box-img-opts
#
## TEST deployment for BOX
#  - name: box-test-aws
#    type: ecsDeploy
#    steps:
#      - IN: box-man
#      - IN: box-t-params
#      - IN: env-test-aws


# VISUALIZER CODE

## CI for VISUALIZER
#  - name: dv-ci
#    type: runCI
#    steps:
#      - IN: dv-repo
#      - OUT: dv-img
#
## manifest gen for VISUALIZER
#  - name: dv-man
#    type: manifest
#    steps:
#      - IN: dv-img
#      - IN: dv-img-opts
#
## TEST deployment for VISUALIZER
#  - name: dv-test
#    type: ecsDeploy
#    steps:
#      - IN: dv-man
#      - IN: dv-params
#      - IN: env-test-aws
